### ISSUE TITLE
Bad request on startup

### ISSUE THREAD

**Issue by Kaoticz** [aimproxy/dotfonts#13]
**Description**
The program shows a window with error 400 as soon as it launches. Search queries also don't work.

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Open DotFonts.
2. The program opens and shows an additional window with the error 400.

**Expected behaviour**
No error window should pop-up. Also, search queries are expected to work.

**Desktop:**
 - DotFonts Version 0.1.3
 - elementary OS 5.1.6 Hera

**Comment by aimproxy** [comment]
Google Fonts API have changed and I am no longer using elementary OS... The only development this application could have from here is porting to FlatHub for the Gnome 3.26 which is what I'm using now.

**Comment by sergius02** [comment]
Hi!

In this case the error is caused by a typo in the request URI, i've made a PR to fix it 😸️

**Comment by aimproxy** [comment]
In case that interests you I'm developing a new app called Transport take a look at the mockups: https://gitlab.gnome.org/aimproxy/transport-mockups/-/blob/master/transport-window.svg
