### ISSUE TITLE
AppCenter Review: Screenshots must show default settings

### ISSUE THREAD

**Issue by danirabbit** [aimproxy/dotfonts#4]
I've marked the latest release of DotFonts as "Needs Fixing" because screenshots do not show the default set of window controls. Screenshots should show an unmodified system, so that the user will see a screenshot that fully represents what they will see of your app when they install it.

For more information see publishing requirements: https://github.com/elementary/houston/wiki/Before-You-Publish#appdata-and-oars

**Comment by aimproxy** [comment]
Done
